######################################################################
# Automatically generated by qmake (2.01a) qui Ago 31 15:21:31 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . UnitConverter
INCLUDEPATH += .

# Input
HEADERS += converter.h \
           menu.h \
           menu_ui.h 
FORMS += menu_ui.ui
SOURCES += converter.cpp \
           main.cpp \
           menu.cpp 
